# cmd: conda build . -c conda-forge
package:
    name: mpack
    version: "0.6.8"

source:
    path: .

requirements:
    build:
        - autoconf
        - automake
        - libtool
        - conda-forge::gcc_linux-64=11.2.0
        - conda-forge::gxx_linux-64=11.2.0
        - conda-forge::gfortran_linux-64=11.2.0
        - conda-forge::blas
        - conda-forge::openblas # [linux]
    run:
        - autoconf
        - automake
        - libtool
        - conda-forge::gcc_linux-64=11.2.0
        - conda-forge::gxx_linux-64=11.2.0
        - conda-forge::gfortran_linux-64=11.2.0
        - conda-forge::blas
        - conda-forge::openblas # [linux]
